/**
 * atkma_transpiler.js
 * ATKMA — Adhere To Konwisdom Make Agreement
 * Supplemental code exchange engine
 *
 * Licensed under the Toadstool Open Source Software License v1.0.0
 * Copyright (C) 2026 Tyler Blankenship
 *
 * PURPOSE:
 * Reads a source file, detects all ATKMA patterns for a given target,
 * exhausts each affected block, generates supplemental replacement code,
 * writes a new .atkma.out file, and logs every exchange to atkma/exchanges/.
 *
 * NEVER modifies the original source file.
 * NEVER uses var.
 * NEVER uses bare catch(e).
 */

'use strict';

const fs   = require('fs');
const path = require('path');

// ── TOADSTOOL LICENSE HEADER ──────────────────────────────────────────────────
const TOADSTOOL_HEADER = `// Licensed under the Toadstool Open Source Software License v1.0.0
// Copyright (C) 2026 Tyler Blankenship
// Generated by ATKMA transpiler v1.0.0
// This file was produced by the ATKMA exchange process.
// Original file preserved alongside this output.
// See LICENSE_TOADSTOOL.md for full terms.
`;

// ── LOAD REGISTRY ─────────────────────────────────────────────────────────────
function loadRegistry(registryPath) {
  const resolved = registryPath || path.join(__dirname, 'atkma.registry.json');
  if (!fs.existsSync(resolved)) {
    throw new Error(`ATKMA registry not found at: ${resolved}`);
  }
  return JSON.parse(fs.readFileSync(resolved, 'utf8'));
}

// ── DETECT: find all pattern matches in source lines ─────────────────────────
function detect(lines, patternEntry) {
  const regex   = new RegExp(patternEntry.pattern, 'g');
  const matches = [];

  lines.forEach((line, idx) => {
    if (regex.test(line)) {
      matches.push({
        pattern_id:  patternEntry.id,
        line_number: idx + 1,
        line_index:  idx,
        original:    line,
        description: patternEntry.description,
        source_lang: patternEntry.source_lang,
        supp_lang:   patternEntry.supp_lang,
        exchange_fn: patternEntry.exchange_fn,
      });
    }
    regex.lastIndex = 0;
  });

  return matches;
}

// ── EXCHANGE FUNCTIONS ────────────────────────────────────────────────────────

function exchange_var(line, context) {
  // Determine const vs let by scanning ahead for reassignment
  const indent    = line.match(/^(\s*)/)[1];
  const after_var = line.replace(/\bvar\b/, '');
  const name_match = after_var.match(/^\s*([a-zA-Z_$][a-zA-Z0-9_$]*)/);
  const name      = name_match ? name_match[1] : null;

  // Default to const — if context shows reassignment use let
  let keyword = 'const';
  if (context && context.all_lines && name) {
    const rest = context.all_lines.slice(context.line_index + 1);
    const reassigned = rest.some(l => {
      const re = new RegExp(`\\b${name}\\s*=(?!=)`, 'g');
      return re.test(l);
    });
    if (reassigned) keyword = 'let';
  }

  return {
    supplement:  line.replace(/\bvar\b/, keyword),
    agree:       'yes',
    keyword_used: keyword,
    note:        `var exchanged with ${keyword} via ATKMA exchange_var`,
  };
}

function exchange_var_for(line, context) {
  // for loop var is always let — block scoped iteration
  return {
    supplement: line.replace(/\bvar\b/, 'let'),
    agree:      'yes',
    note:       'var in for loop exchanged with let via ATKMA exchange_var_for',
  };
}

function exchange_catch_e_used(line, context) {
  // Detect if e is used in subsequent lines until closing brace
  const indent  = line.match(/^(\s*)/)[1];
  let   body    = '';
  let   depth   = 0;
  let   started = false;

  if (context && context.all_lines) {
    for (let i = context.line_index; i < context.all_lines.length; i++) {
      const l = context.all_lines[i];
      if (l.includes('{')) { depth++; started = true; }
      if (l.includes('}')) { depth--; }
      if (started && depth === 0) break;
      body += l + '\n';
    }
  }

  // Replace e.message, e.stack, e.toString(), String(e), console.log(e)
  const supp = line
    .replace(/catch\s*\(\s*e\s*\)/, 'catch(error: unknown)')
    + '\n' +
    `${indent}  const _atkma_msg = error instanceof Error ? error.message : String(error);`;

  return {
    supplement: supp,
    agree:      'yes',
    note:       'catch(e) with e used — exchanged with typed catch via ATKMA exchange_catch_e_used',
    body_patch: {
      find:    /\be\.message\b/g,
      replace: '_atkma_msg',
    },
  };
}

function exchange_catch_e_unused(line) {
  // Empty catch — Deno supports parameterless catch
  const supp = line.replace(/catch\s*\(\s*e\s*\)\s*\{\s*\}/, 'catch { }');
  return {
    supplement: supp,
    agree:      'yes',
    note:       'empty catch(e) exchanged with catch { } via ATKMA exchange_catch_e_unused',
  };
}

function exchange_implicit_any(line) {
  const supp = line
    .replace(/catch\s*\(\s*e\s*\)/, 'catch(error: unknown)')
    .replace(/\be\.message\b/g, '(error instanceof Error ? error.message : String(error))')
    .replace(/\be\.stack\b/g,   '(error instanceof Error ? error.stack   : undefined)')
    .replace(/\be\b/g,          'error');
  return {
    supplement: supp,
    agree:      'yes',
    note:       'implicit any catch exchanged via ATKMA exchange_implicit_any',
  };
}

const EXCHANGE_FNS = {
  exchange_var,
  exchange_var_for,
  exchange_catch_e_used,
  exchange_catch_e_unused,
  exchange_implicit_any,
};

// ── TRANSPILE: main engine ────────────────────────────────────────────────────
function transpile(sourcePath, targetRuntime, options = {}) {
  const registryPath = options.registry ||
    path.join(__dirname, 'atkma.registry.json');

  const registry = loadRegistry(registryPath);
  const source   = fs.readFileSync(sourcePath, 'utf8');
  const lines    = source.split('\n');

  // Filter patterns for this target
  const active_patterns = registry.patterns.filter(p =>
    p.targets.includes(targetRuntime)
  );

  const exchanges    = [];
  const applied_idxs = new Set();
  const output_lines = [...lines];

  // DETECT phase — collect all matches
  for (const pattern_entry of active_patterns) {
    const matches = detect(lines, pattern_entry);
    for (const match of matches) {
      exchanges.push({ ...match, status: 'detected' });
    }
  }

  // EXHAUST + SUPPLEMENT + AGREE + EXCHANGE phase
  for (const exchange of exchanges) {
    if (applied_idxs.has(exchange.line_index)) continue;

    const fn = EXCHANGE_FNS[exchange.exchange_fn];
    if (!fn) {
      exchange.status = 'failed';
      exchange.note   = `No exchange function found for: ${exchange.exchange_fn}`;
      continue;
    }

    const context = {
      all_lines:  lines,
      line_index: exchange.line_index,
    };

    let result;
    try {
      result = fn(exchange.original, context);
    } catch(error) {
      exchange.status = 'failed';
      exchange.note   = error instanceof Error ? error.message : String(error);
      continue;
    }

    if (result.agree === 'yes') {
      output_lines[exchange.line_index] = result.supplement;
      applied_idxs.add(exchange.line_index);
      exchange.status     = 'exchanged';
      exchange.supplement = result.supplement;
      exchange.note       = result.note;

      // Apply body patches if present
      if (result.body_patch) {
        for (let i = exchange.line_index + 1; i < output_lines.length; i++) {
          output_lines[i] = output_lines[i].replace(
            result.body_patch.find,
            result.body_patch.replace
          );
        }
      }
    } else {
      exchange.status = 'pending';
      exchange.note   = result.note || 'AGREE not confirmed';
    }
  }

  // Determine output file path and extension
  const ext      = path.extname(sourcePath);
  const base     = path.basename(sourcePath, ext);
  const dir      = path.dirname(sourcePath);
  const out_ext  = exchange.supp_lang === 'typescript' ? '.ts' : ext;
  const out_path = path.join(dir, `${base}.atkma.out${out_ext || ext}`);

  // Write output file with Toadstool header
  const output_content = TOADSTOOL_HEADER +
    `// Source: ${sourcePath}\n` +
    `// Target: ${targetRuntime}\n` +
    `// ATKMA exchanges applied: ${applied_idxs.size}\n\n` +
    output_lines.join('\n');

  fs.writeFileSync(out_path, output_content);

  // Write exchange log
  const timestamp   = new Date().toISOString().replace(/[:.]/g, '-');
  const log_dir     = path.join(path.dirname(__dirname), 'atkma', 'exchanges');
  fs.mkdirSync(log_dir, { recursive: true });

  const log_path = path.join(log_dir, `${timestamp}-${base}.atkma`);
  const log_lines = [
    `ATKMA v1.0`,
    `TARGET      : ${targetRuntime}`,
    `SOURCE_FILE : ${sourcePath}`,
    `OUTPUT_FILE : ${out_path}`,
    `TIMESTAMP   : ${new Date().toISOString()}`,
    `EXCHANGES   : ${exchanges.length} detected, ${applied_idxs.size} applied`,
    ``,
  ];

  for (const ex of exchanges) {
    log_lines.push(`-- EXCHANGE: ${ex.pattern_id} at line ${ex.line_number} --`);
    log_lines.push(`STATUS      : ${ex.status}`);
    log_lines.push(`SOURCE_LANG : ${ex.source_lang}`);
    log_lines.push(`SUPP_LANG   : ${ex.supp_lang}`);
    log_lines.push(`NOTE        : ${ex.note || ''}`);
    log_lines.push(`ORIGINAL    : ${ex.original}`);
    log_lines.push(`SUPPLEMENT  : ${ex.supplement || '(none)'}`);
    log_lines.push(`AGREE       : ${ex.status === 'exchanged' ? 'yes' : 'pending'}`);
    log_lines.push(`-- END EXCHANGE --`);
    log_lines.push(``);
  }

  fs.writeFileSync(log_path, log_lines.join('\n'));

  return {
    source_path:      sourcePath,
    output_path:      out_path,
    log_path,
    exchanges_total:  exchanges.length,
    exchanges_applied: applied_idxs.size,
    exchanges_failed: exchanges.filter(ex => ex.status === 'failed').length,
    exchanges_pending: exchanges.filter(ex => ex.status === 'pending').length,
    exchanges,
  };
}

// ── CLI ENTRY ─────────────────────────────────────────────────────────────────
if (require.main === module) {
  const args   = process.argv.slice(2);
  const source = args[0];
  const target = args[1] || 'deno';

  if (!source) {
    console.error('Usage: node atkma_transpiler.js <source_file> [target_runtime]');
    console.error('       target_runtime defaults to: deno');
    process.exit(1);
  }

  if (!fs.existsSync(source)) {
    console.error(`Source file not found: ${source}`);
    process.exit(1);
  }

  console.log(`ATKMA transpiler v1.0.0`);
  console.log(`Source : ${source}`);
  console.log(`Target : ${target}`);
  console.log(`Processing...`);

  const result = transpile(source, target);

  console.log(`\nComplete.`);
  console.log(`Output       : ${result.output_path}`);
  console.log(`Log          : ${result.log_path}`);
  console.log(`Exchanges    : ${result.exchanges_applied} applied,` +
    ` ${result.exchanges_failed} failed,` +
    ` ${result.exchanges_pending} pending`);

  process.exit(result.exchanges_failed > 0 ? 1 : 0);
}

module.exports = { transpile, detect, loadRegistry, EXCHANGE_FNS };
